name: React Docker ACR ACI Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-and-deploy-react:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        docker login myreactdotnetacr.azurecr.io \
        -u ${{ secrets.ACR_USERNAME }} \
        -p ${{ secrets.ACR_PASSWORD }}

    - name: Build React Docker Image
      run: |
        docker build --no-cache -t myreactdotnetacr.azurecr.io/react_repo:${{ github.sha }} .

    - name: Push React Docker Image
      run: |
        docker push myreactdotnetacr.azurecr.io/react_repo:${{ github.sha }}

    - name: Delete Existing React Container
      run: |
        az container delete \
          --resource-group virtualmachine1 \
          --name react-container \
          --yes || true

    - name: Deploy React Container to ACI
      run: |
        az container create \
          --resource-group virtualmachine1 \
          --name react-container \
          --image myreactdotnetacr.azurecr.io/react_repo:${{ github.sha }} \
          --registry-login-server myreactdotnetacr.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label rakshitha-react-app-123 \
          --ports 80 \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5